import {nanoid} from "@reduxjs/toolkit";

export const allDays = [
    [],
    [
        {
            id: nanoid(),
            name: "Personal Time",
            start: "6:00",
            end: "7:00",
            type: "free",
            step: 1,
        },
        {
            id: nanoid(),
            name: "Family Time",
            start: "7:00",
            end: "8:00",
            type: "free",
            step: 1,
        },
        {
            id: nanoid(),
            name: "Mindset Moment",
            start: "8:00",
            end: "8:30",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Market Update",
            start: "8:30",
            end: "9:00",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Hot Lead FU",
            start: "9:00",
            end: "9:30",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "FLEX TIME",
            start: "9:30",
            end: "10:00",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "New Partner Appointment",
            start: "10:00",
            end: "10:30",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Borrower Pre-Purchase Consults",
            start: "10:30",
            end: "12:00",
            type: "market",
            step: 1.5,
        },
        {
            id: nanoid(),
            name: "Email/Alerts",
            start: "12:00",
            end: "12:30",
            type: "email",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Mid Day Reset",
            start: "12:30",
            end: "12:45",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Nutrition",
            start: "13:00",
            end: "13:30",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Agent Weekly FU",
            start: "13:30",
            end: "14:00",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Scripts/Role Play",
            script: 1,
            start: "14:00",
            end: "14:30",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Scripts/Role Play",
            script: 2,
            start: "14:30",
            end: "15:00",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Borrower Pre-Purchase Consults",
            start: "15:00",
            end: "16:30",
            type: "market",
            step: 1.5,
        },
        {
            id: nanoid(),
            name: "Final Calls",
            start: "16:30",
            end: "17:00",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Milestone Updates",
            start: "17:00",
            end: "18:00",
            type: "market",
            step: 1,
        },
        {
            id: nanoid(),
            name: "5 DB Calls/Social Media",
            start: "18:00",
            end: "18:30",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Personal Time",
            start: "18:30",
            end: "19:00",
            type: "free",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Family Time",
            start: "19:00",
            end: "20:00",
            type: "free",
            step: 1,
        }
    ],
    [
        {
            id: nanoid(),
            name: "Personal Time",
            start: "6:00",
            end: "7:00",
            type: "free",
            step: 1,
        },
        {
            id: nanoid(),
            name: "Family Time",
            start: "7:00",
            end: "8:00",
            type: "free",
            step: 1,
        },
        {
            id: nanoid(),
            name: "Mindset Moment",
            start: "8:00",
            end: "8:30",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Market Update",
            start: "8:30",
            end: "9:00",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Hot Lead FU",
            start: "9:00",
            end: "9:30",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "FLEX TIME",
            start: "9:30",
            end: "10:00",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "New Partner Appointment",
            start: "10:00",
            end: "10:30",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Borrower Pre-Purchase Consults",
            start: "10:30",
            end: "12:00",
            type: "market",
            step: 1.5,
        },
        {
            id: nanoid(),
            name: "Email/Alerts",
            start: "12:00",
            end: "12:30",
            type: "email",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Mid Day Reset",
            start: "12:30",
            end: "12:45",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Nutrition",
            start: "13:00",
            end: "13:30",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Agent Weekly FU",
            start: "13:30",
            end: "14:00",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Scripts/Role Play",
            script: 1,
            start: "14:00",
            end: "14:30",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Scripts/Role Play",
            script: 2,
            start: "14:30",
            end: "15:00",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Borrower Pre-Purchase Consults",
            start: "15:00",
            end: "16:30",
            type: "market",
            step: 1.5,
        },

        {
            id: nanoid(),
            name: "Final Calls",
            start: "16:30",
            end: "17:00",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "5 DB Calls/Social Media",
            start: "17:00",
            end: "18:00",
            type: "market",
            step: 1,
        },
        {
            id: nanoid(),
            name: "Personal Time",
            start: "18:00",
            end: "19:00",
            type: "free",
            step: 1,
        },
        {
            id: nanoid(),
            name: "Family Time",
            start: "19:00",
            end: "20:00",
            type: "free",
            step: 1,
        },
    ],
    [
        {
            id: nanoid(),
            name: "Personal Time",
            start: "6:00",
            end: "7:00",
            type: "free",
            step: 1,
        },
        {
            id: nanoid(),
            name: "Family Time",
            start: "7:00",
            end: "8:00",
            type: "free",
            step: 1,
        },
        {
            id: nanoid(),
            name: "Mindset Moment",
            start: "8:00",
            end: "8:30",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Market Update",
            start: "8:30",
            end: "9:00",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Hot Lead FU",
            start: "9:00",
            end: "9:30",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "FLEX TIME",
            start: "9:30",
            end: "10:00",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "New Partner Appointment",
            start: "10:00",
            end: "10:30",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Borrower Pre-Purchase Consults",
            start: "10:30",
            end: "12:00",
            type: "market",
            step: 1.5,
        },
        {
            id: nanoid(),
            name: "Email/Alerts",
            start: "12:00",
            end: "12:30",
            type: "email",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Mid Day Reset",
            start: "12:30",
            end: "12:45",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Nutrition",
            start: "13:00",
            end: "13:30",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Thank You Cards",
            start: "13:30",
            end: "14:00",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Scripts/Role Play",
            script: 1,
            start: "14:00",
            end: "14:30",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Scripts/Role Play",
            script: 2,
            start: "14:30",
            end: "15:00",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Borrower Pre-Purchase Consults",
            start: "15:00",
            end: "16:30",
            type: "market",
            step: 1.5,
        },
        {
            id: nanoid(),
            name: "Final Calls",
            start: "16:30",
            end: "17:00",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Milestone Updates",
            start: "17:00",
            end: "17:30",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "5 DB Calls/Social Media",
            start: "17:30",
            end: "18:00",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Borrower Pre-Purchase Consults",
            start: "18:30",
            end: "20:00",
            type: "market",
            step: 1.5,
        }
    ],
    [
        {
            id: nanoid(),
            name: "Personal Time",
            start: "6:00",
            end: "7:00",
            type: "free",
            step: 1,
        },
        {
            id: nanoid(),
            name: "Family Time",
            start: "7:00",
            end: "8:00",
            type: "free",
            step: 1,
        },
        {
            id: nanoid(),
            name: "Mindset Moment",
            start: "8:00",
            end: "8:30",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Market Update",
            start: "8:30",
            end: "9:00",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Hot Lead FU",
            start: "9:00",
            end: "9:30",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "FLEX TIME",
            start: "9:30",
            end: "10:00",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "New Partner Appointment",
            start: "10:00",
            end: "10:30",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Borrower Pre-Purchase Consults",
            start: "10:30",
            end: "12:00",
            type: "market",
            step: 1.5,
        },
        {
            id: nanoid(),
            name: "Email/Alerts",
            start: "12:00",
            end: "12:30",
            type: "email",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Mid Day Reset",
            start: "12:30",
            end: "12:45",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Nutrition",
            start: "13:00",
            end: "13:30",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Agent Weekly FU",
            start: "13:30",
            end: "14:00",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Scripts/Role Play",
            script: 1,
            start: "14:00",
            end: "14:30",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Scripts/Role Play",
            script: 2,
            start: "14:30",
            end: "15:00",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Borrower Pre-Purchase Consults",
            start: "15:00",
            end: "16:30",
            type: "market",
            step: 1.5,
        },
        {
            id: nanoid(),
            name: "Final Calls",
            start: "16:30",
            end: "17:00",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "5 DB Calls/Social Media",
            start: "17:00",
            end: "17:30",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Milestone Updates",
            start: "17:30",
            end: "18:00",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Personal Time",
            start: "18:00",
            end: "19:00",
            type: "free",
            step: 1,
        },
        {
            id: nanoid(),
            name: "Family Time",
            start: "19:00",
            end: "20:00",
            type: "free",
            step: 1,
        }
    ],
    [
        {
            id: nanoid(),
            name: "Personal Time",
            start: "6:00",
            end: "7:00",
            type: "free",
            step: 1,
        },
        {
            id: nanoid(),
            name: "Family Time",
            start: "7:00",
            end: "8:00",
            type: "free",
            step: 1,
        },
        {
            id: nanoid(),
            name: "Mindset Moment",
            start: "8:00",
            end: "8:30",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Market Update",
            start: "8:30",
            end: "9:00",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Hot Lead FU",
            start: "9:00",
            end: "9:30",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "FLEX TIME",
            start: "9:30",
            end: "10:00",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "New Partner Appointment",
            start: "10:00",
            end: "10:30",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Borrower Pre-Purchase Consults",
            start: "10:30",
            end: "12:00",
            type: "market",
            step: 1.5,
        },
        {
            id: nanoid(),
            name: "Email/Alerts",
            start: "12:00",
            end: "12:30",
            type: "email",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Mid Day Reset",
            start: "12:30",
            end: "12:45",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Nutrition",
            start: "13:00",
            end: "13:30",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Agent Weekly FU",
            start: "13:30",
            end: "14:00",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Scripts/Role Play",
            script: 1,
            start: "14:00",
            end: "14:30",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Scripts/Role Play",
            script: 2,
            start: "14:30",
            end: "15:00",
            type: "mindset",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Borrower Pre-Purchase Consults",
            start: "15:00",
            end: "16:30",
            type: "market",
            step: 1.5,
        },
        {
            id: nanoid(),
            name: "Final Calls",
            start: "16:30",
            end: "17:00",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Milestone Updates",
            start: "17:00",
            end: "18:00",
            type: "market",
            step: 1,
        },
        {
            id: nanoid(),
            name: "5 DB Calls/Social Media",
            start: "18:00",
            end: "18:30",
            type: "market",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Personal Time",
            start: "18:30",
            end: "19:00",
            type: "free",
            step: 0.5,
        },
        {
            id: nanoid(),
            name: "Family Time",
            start: "19:00",
            end: "20:00",
            type: "free",
            step: 1,
        },
    ],
    [],
];

export default allDays;